FROM node:20-bookworm-slim

WORKDIR /app

COPY package*.json ./
COPY pnpm-lock.yaml* ./

RUN npm ci --legacy-peer-deps

COPY . .

ARG NEXT_PUBLIC_SITE_URL=https://www.nivaranfoundation.org
ARG NEXT_PUBLIC_APP_URL=https://www.nivaranfoundation.org
ARG NEXT_PUBLIC_API_BASE_URL=https://api.nivaranfoundation.org
ARG AUTH_API_BASE_URL=https://api.nivaranfoundation.org
ARG NEXT_PUBLIC_ENABLE_VERCEL_ANALYTICS=false
ARG NEXT_PUBLIC_SUPABASE_URL=
ARG NEXT_PUBLIC_SUPABASE_ANON_KEY=
ARG NEXT_PUBLIC_SQUARE_APP_ID=
ARG NEXT_PUBLIC_SQUARE_LOCATION_ID=

ENV NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL \
    NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL \
    NEXT_PUBLIC_API_BASE_URL=$NEXT_PUBLIC_API_BASE_URL \
    AUTH_API_BASE_URL=$AUTH_API_BASE_URL \
    NEXT_PUBLIC_ENABLE_VERCEL_ANALYTICS=$NEXT_PUBLIC_ENABLE_VERCEL_ANALYTICS \
    NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL \
    NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY \
    NEXT_PUBLIC_SQUARE_APP_ID=$NEXT_PUBLIC_SQUARE_APP_ID \
    NEXT_PUBLIC_SQUARE_LOCATION_ID=$NEXT_PUBLIC_SQUARE_LOCATION_ID \
    NEXT_TELEMETRY_DISABLED=1

RUN npm run build

ENV NODE_ENV=production \
    PORT=3000 \
    HOSTNAME=0.0.0.0

EXPOSE 3000

CMD ["npm", "run", "start", "--", "--hostname", "0.0.0.0", "--port", "3000"]
